M48
; DRILL file {KiCad 7.0.10} date Wednesday, January 17, 2024 at 03:42:59 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-17T15:42:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0400
%
G90
G05
T1
X2.6Y-1.8
X2.6Y-1.9
X2.6Y-2.0
X2.6Y-2.1
X2.6Y-2.2
X2.6Y-2.3
X2.6Y-2.4
X3.2Y-1.8
X3.2Y-1.9
X3.2Y-2.0
X3.2Y-2.1
X3.2Y-2.2
X3.2Y-2.3
X3.2Y-2.4
M30
