M48
; DRILL file {KiCad 7.0.10} date Tuesday, January 23, 2024 at 05:59:53 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-23T17:59:53-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0335
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0374
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0400
%
G90
G05
T1
X3.3Y-3.2
X3.3Y-3.5
X4.2Y-3.2
X4.2Y-3.5
T2
X3.5031Y-5.1
X3.6016Y-5.1
X3.7Y-5.1
T3
X5.0Y-3.0
X5.0Y-3.6
X5.1Y-3.0
X5.1Y-3.6
X5.2Y-3.0
X5.2Y-3.6
X5.3Y-3.0
X5.3Y-3.6
X5.4Y-3.0
X5.4Y-3.6
X5.5Y-3.0
X5.5Y-3.6
X5.6Y-3.0
X5.6Y-3.6
M30
